config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :comments, only: [:create, :destroy]
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  attribute :new_image
  validates :caption, presence: true
  validate :new_image_check

  def new_image_check
    if new_image.present?
      unless new_image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:new_image, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      unless image.attached? 
        errors.add(:new_image, 'ファイルを添付してください')
      end
    end
  end

  before_save do
    self.image = new_image if new_image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  attribute :new_avatar

  validates :name, presence: true, length: { maximum: 50 }  
  validates :username, presence: true, length: { maximum: 50 } ,uniqueness: true 
  validates :description, presence: true, length: { maximum: 1000 }
  validate :new_avatar_check

  def new_avatar_check
    if new_avatar.present?
      unless new_avatar.content_type.in?(%w(image/jpeg image/png))
        errors.add(:new_avatar, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      unless avatar.attached? 
        errors.add(:new_avatar, 'ファイルを添付してください')
      end
    end
  end

  before_save do
    self.avatar = new_avatar if new_avatar
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :description, :new_avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :new_avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to posts_path, notice: "コメントを保存しました。"
    else
      render template: "posts/index"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to posts_path, notice: "コメントを削除しました。"
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.attributes = {
      user_id: current_user.id  
    }
    if @post.save
      redirect_to @post, notice: '投稿を保存しました'
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "投稿を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "投稿を削除しました。"
  end

  private

  def post_params
    params.require(:post).permit(:caption, :new_image)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telegram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container mb-5">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_delete_modal.html.erb
<div class="modal fade" id="delete-post">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">投稿削除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= image_tag post.image.variant(combine_options: { resize: "800x800^", crop: "800x800+0+0", gravity: :center }).processed, class: "img-fluid" %></p>
        <p><%= "#{post.caption}を削除しますか？" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        <%= link_to "削除", post_path(post), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render "shared/errors", obj: post %>
  <div class="form-group">
    <%= f.label :new_image %>
    <%= f.file_field :new_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_area :caption, class: "form-control", row: "7" %>
  </div>
  <p>
    <%= f.submit t(".post"), class: "btn btn-block btn-primary" %>
  </p>
  <p>
    <%= link_to t(".back"), :back, class: "btn btn-block btn-secondary"  %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<div class="card mb-5">
  <div class="card-header bg-transparent">
    <% if post.user.avatar.attached? %>
      <%= image_tag post.user.avatar.variant(combine_options: { resize: "32x32", crop: "32x32+0+0", gravity: :center }).processed, class: "img-fluid rounded-circle" %>
    <% else %>
      <%= image_tag "no_image", class: "img-fluid rounded-circle" %>
    <% end %>
    <%= post.user.name %>
  </div>
  <%= link_to post do  %>
    <!-- mini_magickのメソッドを使用して画像サイズを変更して表示 -->
    <% if post.image.attached? %>
      <%= image_tag post.image.variant(combine_options: { resize: "800x800^", crop: "800x800+0+0", gravity: :center }).processed, class: "card-img" %>
    <% else %>
      <%= image_tag "no_image", class: "card-img" %>
    <% end %>
  <% end %>
  <div class="card-text">
    <p><%= truncate(post.caption, length: 90) %></p>

    <hr>
    <% post.comments.last(3).each do |comment| %>
      <p>
        <%= image_tag comment.user.avatar.variant(combine_options: { resize: "20x20^", crop: "20x20+0+0", gravity: :center }).processed, class: "img-fluid rounded-circle" %>
        <%= comment.user.name %>
        <%= truncate(comment.body, length: 30) %>
        <% if current_user.id == comment.user.id %>
          <%= link_to t(".delete"), comment_path(comment), method: :delete, data: {confirm: '削除してよろしいですか？'}  %>
        <% end %>
      </p>
    <% end %>

    <%= form_with model: @comment, url: comments_path, class: "form-group row mx-auto", local: true do |f| %>
      <%= f.hidden_field :post_id, value: post.id %>
      <%= f.text_field :body, class: "col-8 form-control" %>
      <%= f.submit t(".submit"), class: "col-4" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-lg-10 mx-auto">
    <div class="logo col-lg-12 mb-3 text-center">
      <h1>Edit Post</h1>
    </div>

    <div class="card">
      <div class="row no-gutters">
        <div class="col-lg-6">
          <% if @post.image.attached? %>
            <%= image_tag @post.image.variant(combine_options: { resize: "800x800^", crop: "800x800+0+0", gravity: :center }).processed, class: "card-img" %>
          <% else %>
            <%= image_tag "no_image", class: "card-img" %>
          <% end %>
        </div>

        <div class="col-lg-6 card-cody">
          <%= render "form", post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="col-8 mx-auto">
  <%= render "shared/errors", obj: @comment %>
  <div class="post">
    <%= render @posts %>
    <%= paginate @posts %>
  </div>
</div>

<script>
  $(window).on('scroll', function() {
      // 画面スクロールの判定用の変数を用意
      scrollHeight = $(document).height();
      scrollPosition = $(window).height() + $(window).scrollTop();

      // 画面のスクロールが下部10%以下になったら
      if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.1) {
        // .postに対し、jscrollを発火
        $('.post').jscroll({
          // 読込中の表示
          loadingHtml: '<div class="text-center"><img src="http://www.mytreedb.com/uploads/mytreedb/loader/ajax_loader_blue_48.gif">読み込み中</div>',
          // 読み込む内容があるリンク
          nextSelector: 'span.next a',
          // 読み込む内容がある場所
          contentSelector: '.post',
        });
      }
  });
</script>

app/views/posts/new.html.erb
<div class="col-lg-6 mx-auto">
  <div class="logo mb-3 text-center">
    <h1><%= t ".title" %></h1>
  </div>
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class="col-lg-10 mx-auto">
  <div class="card">
    <div class="row no-gutters">
      <div class="col-lg-8">
        <% if @post.image.attached? %>
          <%= image_tag @post.image.variant(combine_options: { resize: "800x800^",   crop: "800x800+0+0", gravity: :center }).processed, class: "card-img" %>
        <% else %>
          <%= image_tag "no_image", class: "card-img" %>
        <% end %>
      </div>
      <div class="col-lg-4">
        <div class="card-body">
          <% if @post.user.avatar.attached? %>
              <%= image_tag @post.user.avatar.variant(combine_options: { resize: "32x32", crop: "32x32+0+0", gravity: :center }).processed, class: "img-fluid rounded-circle" %>
          <% else %>
              <%= image_tag "no_image", class: "img-fluid rounded-circle" %>
          <% end %>
          <%= @post.user.name %>
          <hr>
          <div class="scroll">
            <%= @post.caption %>
            <% @post.comments.each do |comment| %>
              <p>
                <%= image_tag comment.user.avatar.variant(combine_options: { resize: "20x20^", crop: "20x20+0+0", gravity: :center }).processed, class: "img-fluid rounded-circle" %>
                <%= comment.user.name %>
                <%= comment.body %>
              </p>
            <% end %>
          </div>
          <%= form_with model: @comment, url: comments_path, class: "form-group row       mx-auto", local: true do |f| %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :body, class: "col-8 form-control" %>
            <%= f.submit t(".submit"), class: "col-4" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <p>
      <%= link_to "Edit Post", edit_post_path(@post), class:"btn btn-block btn-primary"  %>
    </p>
    <p>
      <%= button_tag "削除", class: "btn btn-block btn-warning", data: { toggle: "modal", target: "#delete-post" } %>
    </p>
  <% end %>
</div>

<%= render "delete_modal", post: @post %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="nav navbar-expand-lg navbar-light bg-light fixed-bottom justify-content-center">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="/"><i class="fas fa-home"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/"><i class="fas fa-search"></i></a>
    </li>
    <li class="nav-item">
      <%= link_to new_post_path, class: "nav-link" do  %>
        <i class="far fa-plus-square"></i>
      <% end %>
    </li>
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to edit_user_registration_path, class: "nav-link" do %>
          <i class="far fa-user"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "nav-link" do %>
          <i class="far fa-user"></i>
        <% end %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light nav-fill sticky-top mb-3">

  <%# ロゴ部分 %>
  <div class="nav-item">
    <a class="navbar-brand logo" href="/"><i class="fab fa-instagram"></i>&nbsp; Telegram</a>
  </div>

  <%# メニュー格納時のボタン %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%# メニュー %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="nav-item form-inline mb-2 mb-lg-0" action="/" accept-charset="UTF-8" method="get">
      <input name="utf8" type="hidden" value="&#x2713;" >
      <input type="text" name="q" id="q" value="" class="form-control fas" placeholder="検索" >
    </form>
    <% if user_signed_in? %>
      <%= link_to edit_user_registration_path, class: "nav-item" do %>
        <i class="far fa-user"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "nav-item" do %>
        <i class="far fa-user"></i>
      <% end %>
    <% end %>
  </div>

</nav>